FROM conciseconstructs/sls:g1

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

ENV PATH=$PATH:/home/node/.npm-global/bin

RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo

USER docker